substitutions:
  device_name: "athom-relay-board-x2"
  project_name: "Athom Technology.Relay-Board-X2"
  project_version: "1.0"
  relay1_restore_mode: RESTORE_DEFAULT_OFF
  relay2_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  friendly_name: ""
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-relay-board-x2.yaml

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

button:
  - platform: factory_reset
    name: "Reset"
    id: Reset

  - platform: safe_mode
    name: "Safe Mode"
    internal: false

switch:
  # Relay
  - platform: gpio
    name: "Relay1"
    pin: GPIO5
    id: relay1
    restore_mode: ${relay1_restore_mode}

  - platform: gpio
    name: "Relay2"
    pin: GPIO4
    id: relay2
    restore_mode: ${relay2_restore_mode}

light:
  - platform: status_led
    name: "Status LED"
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO16

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "Mac Address"
     
time:
  - platform: sntp
    id: sntp_time
