substitutions:
  name: "athom-ls-4p-4wire"
  friendly_name: "Athom LED Controller"
  project_name: "athom.ls-4p-4wire"
  project_version: "1.1"
  button_toggle: "true"
  light_restore_mode: RESTORE_DEFAULT_OFF
  number_of_leds: '150'
  led_chipset: WS2801
  led_rgb_order: GRB

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true
  framework:
    version: 2.7.4

api:

ota:

logger:
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-ls-4p-4wire.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
            - light.toggle: leds
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset
sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
    id: Reset

power_supply:
  - id: relay
    pin: GPIO12

light:
  - platform: fastled_spi
    data_pin: GPIO1
    clock_pin: GPIO3
    id: leds
    name: "${friendly_name}"
    power_supply: relay
    chipset: ${led_chipset}
    num_leds: ${number_of_leds}
    rgb_order: ${led_rgb_order}
    restore_mode: ${light_restore_mode}
    effects:
      - addressable_rainbow:
      - addressable_scan:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true

time:
  - platform: sntp
    id: my_time
